name: Test

on:
  - push
  - pull_request

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '12'
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: '4.11.1'
          run_install: 'true'
      - run: pnpm test
